{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview",
    "module": "flutter_inappwebview_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_profile-1.0.aar",
          "url": "flutter_inappwebview_profile-1.0.aar",
          "size": 354066,
          "sha512": "e4dc9a27c917c80990df9305f7c6a7550da3cab62fc1957131b7dab324d53f0cb109c52901e8dd3f223d6af508dd9e29966f821e27b1ef08d40ea287b7f87a3b",
          "sha256": "0517b733bf726d09875059ad84dde2fefd7c57c9558a5ac1b0fab40bd0a87aa4",
          "sha1": "7b0e9140153918726b431c567aa3d16510b4a908",
          "md5": "57fba86d7764e34c7b9807d4ba0728b1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_profile-1.0.aar",
          "url": "flutter_inappwebview_profile-1.0.aar",
          "size": 354066,
          "sha512": "e4dc9a27c917c80990df9305f7c6a7550da3cab62fc1957131b7dab324d53f0cb109c52901e8dd3f223d6af508dd9e29966f821e27b1ef08d40ea287b7f87a3b",
          "sha256": "0517b733bf726d09875059ad84dde2fefd7c57c9558a5ac1b0fab40bd0a87aa4",
          "sha1": "7b0e9140153918726b431c567aa3d16510b4a908",
          "md5": "57fba86d7764e34c7b9807d4ba0728b1"
        }
      ]
    }
  ]
}
