{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9329,
          "sha512": "d21e64e6718b1df0d50560117b1846832836740d919b28baa6067bfc9fa8ad50ab80ff5a19bc6df12e1107b175639f2175a5ee5d0e75ca310952dec7b7adeda7",
          "sha256": "6135cd0b5cdd5e63010364b0ed8a00bbfd32d748ca82c506c49f53e100d5d4d3",
          "sha1": "ee949c306b2f11f0fd09df14f477197cddcec6ce",
          "md5": "7ee5fb47d419a2c4ec5f46fb39d5a078"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9329,
          "sha512": "d21e64e6718b1df0d50560117b1846832836740d919b28baa6067bfc9fa8ad50ab80ff5a19bc6df12e1107b175639f2175a5ee5d0e75ca310952dec7b7adeda7",
          "sha256": "6135cd0b5cdd5e63010364b0ed8a00bbfd32d748ca82c506c49f53e100d5d4d3",
          "sha1": "ee949c306b2f11f0fd09df14f477197cddcec6ce",
          "md5": "7ee5fb47d419a2c4ec5f46fb39d5a078"
        }
      ]
    }
  ]
}
