{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9652,
          "sha512": "2c181632dbfd571673aac2fb153070b3ec423dc036e2aba0ac1b9faa261a44cf8375b5194c1669a2ce37fa4aa9134efb84dae8f024c8ed12367e4d9f323691d4",
          "sha256": "e7635d71870d22bd503ca291bafb065ecaa80f8e1e585e7f1d5a597c36c1991f",
          "sha1": "7722a331f6c8768a3e4c1afb4bb058cdd25ec3d1",
          "md5": "f5438e9292712244dc9963b27fc71955"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9652,
          "sha512": "2c181632dbfd571673aac2fb153070b3ec423dc036e2aba0ac1b9faa261a44cf8375b5194c1669a2ce37fa4aa9134efb84dae8f024c8ed12367e4d9f323691d4",
          "sha256": "e7635d71870d22bd503ca291bafb065ecaa80f8e1e585e7f1d5a597c36c1991f",
          "sha1": "7722a331f6c8768a3e4c1afb4bb058cdd25ec3d1",
          "md5": "f5438e9292712244dc9963b27fc71955"
        }
      ]
    }
  ]
}
