{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-debug.aar",
          "url": "connectivity_plus-1.0-debug.aar",
          "size": 9367,
          "sha512": "e7be1fe77da8a3014b9cfa8f5a9c902073d029f0ad052b57449a330dd2ef7de0fd84fd6d1762ed4d1541144ef4b9008c8d3e154a161f49778ca9d932fb610b65",
          "sha256": "623a89756fb453084ae2dbeea605043496d940cf741ee7d4a445c14fa8b6881c",
          "sha1": "54d47fe39924b66542ff7cd1af677b6f7117f372",
          "md5": "e81bc47d1170812045b7bdf6b237bc06"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-debug.aar",
          "url": "connectivity_plus-1.0-debug.aar",
          "size": 9367,
          "sha512": "e7be1fe77da8a3014b9cfa8f5a9c902073d029f0ad052b57449a330dd2ef7de0fd84fd6d1762ed4d1541144ef4b9008c8d3e154a161f49778ca9d932fb610b65",
          "sha256": "623a89756fb453084ae2dbeea605043496d940cf741ee7d4a445c14fa8b6881c",
          "sha1": "54d47fe39924b66542ff7cd1af677b6f7117f372",
          "md5": "e81bc47d1170812045b7bdf6b237bc06"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-release.aar",
          "url": "connectivity_plus-1.0-release.aar",
          "size": 9005,
          "sha512": "7261323f08bfdbc99d1f67d20edb51dda9de94e9e35c33387d05c72c1825b8585b0f8769b9e175c8fb89bdcead7545a1c0e4a920062c7ce5aeb78350f4c9e385",
          "sha256": "1672302bf0d6c58aed98006274a531ecfc3b94244f8a3cb02cb753a7a0494b4d",
          "sha1": "fe776e6d776433e2446894e3036db39a004f03b7",
          "md5": "8fb890c3d25fd02775a13f05918288dd"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-release.aar",
          "url": "connectivity_plus-1.0-release.aar",
          "size": 9005,
          "sha512": "7261323f08bfdbc99d1f67d20edb51dda9de94e9e35c33387d05c72c1825b8585b0f8769b9e175c8fb89bdcead7545a1c0e4a920062c7ce5aeb78350f4c9e385",
          "sha256": "1672302bf0d6c58aed98006274a531ecfc3b94244f8a3cb02cb753a7a0494b4d",
          "sha1": "fe776e6d776433e2446894e3036db39a004f03b7",
          "md5": "8fb890c3d25fd02775a13f05918288dd"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-profile.aar",
          "url": "connectivity_plus-1.0-profile.aar",
          "size": 9001,
          "sha512": "3fa4e24c8b665012f9aa0a90243cce157699ade0af0a79f3e8c47ec9d240ec53b8a201f4b28845e0104b82064f51f7225bc519b21d2a01828f2cca4bb4ef2b8a",
          "sha256": "e9dc44e43061d894eb182af84b00ef5753e19596d5bafd5768d9fe75afa66ad5",
          "sha1": "9cedeaf4cde099a473a7c3cf7dd24b7ce6da56c2",
          "md5": "f359d242b71da30ad42f599d3eff9e97"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus-1.0-profile.aar",
          "url": "connectivity_plus-1.0-profile.aar",
          "size": 9001,
          "sha512": "3fa4e24c8b665012f9aa0a90243cce157699ade0af0a79f3e8c47ec9d240ec53b8a201f4b28845e0104b82064f51f7225bc519b21d2a01828f2cca4bb4ef2b8a",
          "sha256": "e9dc44e43061d894eb182af84b00ef5753e19596d5bafd5768d9fe75afa66ad5",
          "sha1": "9cedeaf4cde099a473a7c3cf7dd24b7ce6da56c2",
          "md5": "f359d242b71da30ad42f599d3eff9e97"
        }
      ]
    }
  ]
}
