{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9331,
          "sha512": "0b45ea8f3032738d8d04e971cc190d0e47c2e4334ff08eb0307432482ff27230cd2378ffbe84135c5534b67acdfe9ab45f0cd600c0ea901f3bab015fe83a7216",
          "sha256": "7fab295647c3e7bf36ba4b976d086606dd5e4e1ef40aabb4b3a45660e2c34d68",
          "sha1": "5e40a7ce7da74f1b1b047879e31555c267398cfd",
          "md5": "57a0bf75a4a5c0f3abe6cbf773bbdbeb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9331,
          "sha512": "0b45ea8f3032738d8d04e971cc190d0e47c2e4334ff08eb0307432482ff27230cd2378ffbe84135c5534b67acdfe9ab45f0cd600c0ea901f3bab015fe83a7216",
          "sha256": "7fab295647c3e7bf36ba4b976d086606dd5e4e1ef40aabb4b3a45660e2c34d68",
          "sha1": "5e40a7ce7da74f1b1b047879e31555c267398cfd",
          "md5": "57a0bf75a4a5c0f3abe6cbf773bbdbeb"
        }
      ]
    }
  ]
}
