{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.googlesignin",
    "module": "google_sign_in_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "google_sign_in_android_profile-1.0.aar",
          "url": "google_sign_in_android_profile-1.0.aar",
          "size": 26011,
          "sha512": "5b8cae79bcd6af8d05d74b14f20ce3243431c8e2198f948a9124086659efcd955fa9bae19acf88f47d0983807441ab6623942d3782ba6b0b294045efd38b65b7",
          "sha256": "3830ea30c02745b65083234d4b852e489cf3e5730fe99315b8e36b6d2fd189ba",
          "sha1": "6671d436e07b43e21d15272dece1cf2f2e3dfc91",
          "md5": "a521ae5e0e3ef52adb7c7ecdc9cf0af8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "google_sign_in_android_profile-1.0.aar",
          "url": "google_sign_in_android_profile-1.0.aar",
          "size": 26011,
          "sha512": "5b8cae79bcd6af8d05d74b14f20ce3243431c8e2198f948a9124086659efcd955fa9bae19acf88f47d0983807441ab6623942d3782ba6b0b294045efd38b65b7",
          "sha256": "3830ea30c02745b65083234d4b852e489cf3e5730fe99315b8e36b6d2fd189ba",
          "sha1": "6671d436e07b43e21d15272dece1cf2f2e3dfc91",
          "md5": "a521ae5e0e3ef52adb7c7ecdc9cf0af8"
        }
      ]
    }
  ]
}
