{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-debug.aar",
          "url": "local_auth_android-1.0-debug.aar",
          "size": 51085,
          "sha512": "0eba280e51680aee0834d6f2bcd522ea1d116cdd74abef0a7abe5c3a5c32be3dda820522d393524866b693e44ec2124075700d939aba20356b37535e56abc2d9",
          "sha256": "8c7495a4a568d6665e99c4bcffb54e927fd55d12f9d4e1c08d355697a02a5829",
          "sha1": "8f844e0b5478d524347929d3d3db0430e54957bb",
          "md5": "93ae9937581150871185bdf01c8d9d2b"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-debug.aar",
          "url": "local_auth_android-1.0-debug.aar",
          "size": 51085,
          "sha512": "0eba280e51680aee0834d6f2bcd522ea1d116cdd74abef0a7abe5c3a5c32be3dda820522d393524866b693e44ec2124075700d939aba20356b37535e56abc2d9",
          "sha256": "8c7495a4a568d6665e99c4bcffb54e927fd55d12f9d4e1c08d355697a02a5829",
          "sha1": "8f844e0b5478d524347929d3d3db0430e54957bb",
          "md5": "93ae9937581150871185bdf01c8d9d2b"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-release.aar",
          "url": "local_auth_android-1.0-release.aar",
          "size": 50200,
          "sha512": "077685ae1c5146da86a10e441fe45b7a60819b248f0797760e9d34244d5e93cb53512aaab32bf680e41dbfe6a6e84287a021f7b0595a09552476c39e58adcd27",
          "sha256": "3693de5d4bfeb086510eb1d2719fe2a0918abde8f6022e95d420ac2d03d51803",
          "sha1": "af5623fb912c6dfa73c534498f306266ef60493a",
          "md5": "f669457ca86d5561057c397ab251cc80"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-release.aar",
          "url": "local_auth_android-1.0-release.aar",
          "size": 50200,
          "sha512": "077685ae1c5146da86a10e441fe45b7a60819b248f0797760e9d34244d5e93cb53512aaab32bf680e41dbfe6a6e84287a021f7b0595a09552476c39e58adcd27",
          "sha256": "3693de5d4bfeb086510eb1d2719fe2a0918abde8f6022e95d420ac2d03d51803",
          "sha1": "af5623fb912c6dfa73c534498f306266ef60493a",
          "md5": "f669457ca86d5561057c397ab251cc80"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-profile.aar",
          "url": "local_auth_android-1.0-profile.aar",
          "size": 50202,
          "sha512": "433f747ead92e87944b31e5ce7bbc6c47b74028448227d432f1c8de3f92a7694fcaef2152331b10cb0a75b909918432fb8702aaec440777b5d496ba08a93ea2f",
          "sha256": "1ba4fba5ee552a4b46b8c13e6078a7deb8a4167e5457c9e907167f8a654c8ed9",
          "sha1": "64ec91277700a3096edc992b6aac439ec511bcb2",
          "md5": "75c6eb98b3cb5086b08102d79a0c08ef"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android-1.0-profile.aar",
          "url": "local_auth_android-1.0-profile.aar",
          "size": 50202,
          "sha512": "433f747ead92e87944b31e5ce7bbc6c47b74028448227d432f1c8de3f92a7694fcaef2152331b10cb0a75b909918432fb8702aaec440777b5d496ba08a93ea2f",
          "sha256": "1ba4fba5ee552a4b46b8c13e6078a7deb8a4167e5457c9e907167f8a654c8ed9",
          "sha1": "64ec91277700a3096edc992b6aac439ec511bcb2",
          "md5": "75c6eb98b3cb5086b08102d79a0c08ef"
        }
      ]
    }
  ]
}
