{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cherry.sdk.cherry_sdk",
    "module": "flutter",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.android_id",
          "module": "android_id",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 21716608,
          "sha512": "ef30dcd5db466d10c68b18d825c69595d62e5d96dd67d19f1c679af3d4d18f178d707d71f89f062f6dfb66100cb410191decfad0d4cafd0a75148756cfcb1d56",
          "sha256": "4cc6819299209273448dd797d00a680009282d9fab8d6d4d10f40b9e08547cdf",
          "sha1": "1be9a9b964500f375926529171dc9f936890f0c6",
          "md5": "e6dd0447268dd207889e00fb01633a3c"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.android_id",
          "module": "android_id",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 21716608,
          "sha512": "ef30dcd5db466d10c68b18d825c69595d62e5d96dd67d19f1c679af3d4d18f178d707d71f89f062f6dfb66100cb410191decfad0d4cafd0a75148756cfcb1d56",
          "sha256": "4cc6819299209273448dd797d00a680009282d9fab8d6d4d10f40b9e08547cdf",
          "sha1": "1be9a9b964500f375926529171dc9f936890f0c6",
          "md5": "e6dd0447268dd207889e00fb01633a3c"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.android_id",
          "module": "android_id",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 13201604,
          "sha512": "b4ae54bcb0c26a502d31f717f103e3e6d74291190d0242d77199eb65b5b0b8211a50b76a6562a1f363397d677d14ab130043714136fddeda04a25fb268bfb4a8",
          "sha256": "d5584bfa152776d2e206148378e3fc5bc5250a4ab4d4d0f28c3674b6181944d0",
          "sha1": "917ef9ec05bd175561f67191e5e22b8a651cb77c",
          "md5": "d11b82159139fbc455b20c2d5b177096"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.android_id",
          "module": "android_id",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 13201604,
          "sha512": "b4ae54bcb0c26a502d31f717f103e3e6d74291190d0242d77199eb65b5b0b8211a50b76a6562a1f363397d677d14ab130043714136fddeda04a25fb268bfb4a8",
          "sha256": "d5584bfa152776d2e206148378e3fc5bc5250a4ab4d4d0f28c3674b6181944d0",
          "sha1": "917ef9ec05bd175561f67191e5e22b8a651cb77c",
          "md5": "d11b82159139fbc455b20c2d5b177096"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.android_id",
          "module": "android_id",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 3601464,
          "sha512": "8fd4fc015045cede36c14e272e85554f6e086634ca433cd0cc65a80c8c0d3b579a329c3fb12768201ca59989074384a914260a09869b056ad1e694721b3c3074",
          "sha256": "52c3058d6323548a758e42c9e2ce3e5e44389049d5f0bc86b287c2fedd992c93",
          "sha1": "da1698efae60ba9675a7c20582ce254d6a6922d3",
          "md5": "618cfa94a30a5414025fc266d2dcb911"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.android_id",
          "module": "android_id",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 3601464,
          "sha512": "8fd4fc015045cede36c14e272e85554f6e086634ca433cd0cc65a80c8c0d3b579a329c3fb12768201ca59989074384a914260a09869b056ad1e694721b3c3074",
          "sha256": "52c3058d6323548a758e42c9e2ce3e5e44389049d5f0bc86b287c2fedd992c93",
          "sha1": "da1698efae60ba9675a7c20582ce254d6a6922d3",
          "md5": "618cfa94a30a5414025fc266d2dcb911"
        }
      ]
    }
  ]
}
