{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.googlesignin",
    "module": "google_sign_in_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        }
      ],
      "files": [
        {
          "name": "google_sign_in_android_debug-1.0.aar",
          "url": "google_sign_in_android_debug-1.0.aar",
          "size": 27310,
          "sha512": "aff845388b68aed88c4a530810c968fcf6b24cfcc73c121c01ced5b5362680e48dc64594c385721f465b761e4901a6572976ea97efdafb82ab45800047cf40f5",
          "sha256": "3ac4e374013eea984ba78d244e43a85715ecc2bc05cc28c70131f464ac1e15df",
          "sha1": "e7c038e056987312e90333ea4df88e08c4beac49",
          "md5": "e1176792fed147f57acf2e3d65fcd610"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "google_sign_in_android_debug-1.0.aar",
          "url": "google_sign_in_android_debug-1.0.aar",
          "size": 27310,
          "sha512": "aff845388b68aed88c4a530810c968fcf6b24cfcc73c121c01ced5b5362680e48dc64594c385721f465b761e4901a6572976ea97efdafb82ab45800047cf40f5",
          "sha256": "3ac4e374013eea984ba78d244e43a85715ecc2bc05cc28c70131f464ac1e15df",
          "sha1": "e7c038e056987312e90333ea4df88e08c4beac49",
          "md5": "e1176792fed147f57acf2e3d65fcd610"
        }
      ]
    }
  ]
}
