{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.0.aar",
          "url": "local_auth_android_release-1.0.aar",
          "size": 50200,
          "sha512": "077685ae1c5146da86a10e441fe45b7a60819b248f0797760e9d34244d5e93cb53512aaab32bf680e41dbfe6a6e84287a021f7b0595a09552476c39e58adcd27",
          "sha256": "3693de5d4bfeb086510eb1d2719fe2a0918abde8f6022e95d420ac2d03d51803",
          "sha1": "af5623fb912c6dfa73c534498f306266ef60493a",
          "md5": "f669457ca86d5561057c397ab251cc80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3ad69d7be3a7231aab5525db322fc699f098315f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_release-1.0.aar",
          "url": "local_auth_android_release-1.0.aar",
          "size": 50200,
          "sha512": "077685ae1c5146da86a10e441fe45b7a60819b248f0797760e9d34244d5e93cb53512aaab32bf680e41dbfe6a6e84287a021f7b0595a09552476c39e58adcd27",
          "sha256": "3693de5d4bfeb086510eb1d2719fe2a0918abde8f6022e95d420ac2d03d51803",
          "sha1": "af5623fb912c6dfa73c534498f306266ef60493a",
          "md5": "f669457ca86d5561057c397ab251cc80"
        }
      ]
    }
  ]
}
